[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.24"
evm_version = "shanghai"

remappings = [
    'octant-v2/=lib/octant-v2/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'aave-v3-core/=lib/aave-v3-core/contracts/',
    'spark-protocol-v3/=lib/protocol-v3/contracts/',
]
via-ir = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
